import { CSL } from './csl';

// Source modules, imported in dependency order.
import { XmlJSON, stripXmlProcessingInstruction, parseXml } from './xml/xmljson';
CSL.XmlJSON = XmlJSON;
CSL.stripXmlProcessingInstruction = stripXmlProcessingInstruction;
CSL.parseXml = parseXml;
import './xml/xmldom';
import './system';
import './sort';
import './util/disambig';
import './util/nodes';
import './util/dateparser';
import './engine/build';
import './util/static_locator';
import './util/processor';
import './util/citationlabel';
import './engine/control';
import './output/queue';
import './engine/state';
import './engine/cite';
import './engine/bibliography';
import './util/integration';
import './engine/update';
import './util/locale';
import './util/locale_sniff';
import './node/bibliography';
import './node/choose';
import './node/citation';
import './node/comment';
import './node/date';
import './node/datepart';
import './node/elseif';
import './node/else';
import './node/etal';
import './node/group';
import './node/if';
import './node/conditions';
import './node/condition';
import './util/conditions';
import './node/info';
import './node/institution';
import './node/institutionpart';
import './node/key';
import './node/label';
import './node/layout';
import './node/macro';
import './node/alternative';
import './node/alternativetext';
import './util/names/output';
import './util/names/tests';
import './util/names/truncate';
import './util/names/divide';
import './util/names/join';
import './util/names/common';
import './util/names/constraints';
import './util/names/disambig';
import './util/names/etalconfig';
import './util/names/etal';
import './util/names/render';
import { PublisherOutput } from './util/publishers';
CSL.PublisherOutput = PublisherOutput;
import './util/label';
import './node/name';
import './node/namepart';
import './node/names';
import './node/number';
import './node/sort';
import './node/substitute';
import './node/text';
import './node/intext';
import './attributes/attributes';
import './stack';
import { Parallel } from './util/parallel';
CSL.Parallel = Parallel;
import './util/util';
import './util/transform';
import './obj/token';
import './obj/ambigconfig';
import './obj/blob';
import './obj/number';
import './util/datenode';
import './util/date';
import './util/names/index';
import './util/dates';
import './util/sort';
import './util/substitute';
import './util/number';
import './util/page';
import './util/flipflop';
import './output/formatters';
import './output/formats';
import './registry/registry';
import './disambig/names';
import './disambig/citations';
import './disambig/cites';
import './util/modules';
import './util/name_particles';

export = CSL;
